# Target device
MCU = attiny861
F_CPU = 8000000
LFUSE = 0xE1
HFUSE = 0xDD
EFUSE = 0xFF

# Application files and targets
TARGET = morse

# Place -I options here
CINCS = 
CXXINCS = 

# Place extra C/CXX arguments here
CEXTRA = 
CXXEXTRA = 

# Source files for C compiler
SRC = main.c dac.c audio.c flash.c

# Source files for C++ compiler
CXXSRC = 

# Source files in assembly
ASRC =

# This includes the rest of rules DO NOT DELETE
-include ~/Dropbox/EDA/Makefile.avr.inc
-include ~/.gEDA/Makefile.avr.inc
