# Target device
MCU = attiny861
F_CPU = 8000000
LFUSE = 0xE2
HFUSE = 0xDF
EFUSE = 0x01

# Application files and targets
TARGET = morse

# Place -I options here
CINCS = 
CXXINCS = 

# Place extra C/CXX arguments here
CEXTRA =
CXXEXTRA = 

# Source files for C compiler
SRC = lang.c interface.c spi.c main.c dac.c audio.c flash.c sine.c morse.c leds.c lesson.c play.c

# Source files for C++ compiler
CXXSRC = 

# Source files in assembly
ASRC =

# This includes the rest of rules DO NOT DELETE
-include ~/Dropbox/EDA/Makefile.avr.inc
-include ~/.gEDA/Makefile.avr.inc
